output-format: grouped
strictness: medium
test-warnings: true
doc-warnings: true

pep8:
  disable: ['C0301']  # Example of disabling a warning

pylint:
  run: true  # Ensure pylint is running
  options:
    enable:
      - W0511  # Enable TODO warnings

