name: Code Scanning with TODO Warnings

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Prospector
        run: pip install prospector

      - name: Run Prospector
        run: prospector --output-format=json > prospector-results.json

      - name: Create TODO Warnings
        run: |
          WARNINGS=$(jq -r '.messages[] | select(.source=="pylint" and .code=="fixme") | "\(.location.path):\(.location.line) TODO: \(.message)"' prospector-results.json)

          if [ -n "$WARNINGS" ]; then
            echo "### 🚨 Code Scanning TODO Warnings" >> $GITHUB_STEP_SUMMARY
            echo "$WARNINGS" >> $GITHUB_STEP_SUMMARY
          fi
